version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Where requirements.txt is
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"  # Where Dockerfile is
    schedule:
      interval: "weekly"
