
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A worker.tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
