
name: meta-agent-staging
region: nyc

services:
  - name: web
    environment_slug: docker
    instance_size_slug: basic-xs
    instance_count: 1
    dockerfile_path: Dockerfile
    http_port: 8000
    routes:
      - path: /
    envs:
      - key: ENV
        value: staging
      - key: LOG_LEVEL
        value: debug

  - name: worker
    environment_slug: docker
    instance_size_slug: basic-xs
    instance_count: 1
    dockerfile_path: Dockerfile
    run_command: celery -A worker.tasks worker --loglevel=info
    envs:
      - key: ENV
        value: staging

databases: []

static_sites: []

domains: []
