name: Full CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Show working directory
        run: pwd

      - name: List files in root
        run: ls -la

      - name: Build Docker image
        run: docker build -t meta-agent-builder:latest .

      - name: Run container (Optional – just for debug)
        run: docker run --rm meta-agent-builder:latest

